/* Auto-generated by genmsg_cpp for file /home/rpg711/kinetic_workspace/cs403/compsci403_assignment2/srv/Get3DPointFromDisparitySrv.srv */
#ifndef COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDISPARITYSRV_H
#define COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDISPARITYSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace compsci403_assignment2
{
template <class ContainerAllocator>
struct Get3DPointFromDisparitySrvRequest_ {
  typedef Get3DPointFromDisparitySrvRequest_<ContainerAllocator> Type;

  Get3DPointFromDisparitySrvRequest_()
  : x(0)
  , y(0)
  , disparity(0)
  , fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  , a(0.0)
  , b(0.0)
  {
  }

  Get3DPointFromDisparitySrvRequest_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , disparity(0)
  , fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  , a(0.0)
  , b(0.0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _disparity_type;
  int32_t disparity;

  typedef float _fx_type;
  float fx;

  typedef float _fy_type;
  float fy;

  typedef float _px_type;
  float px;

  typedef float _py_type;
  float py;

  typedef float _a_type;
  float a;

  typedef float _b_type;
  float b;


  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct Get3DPointFromDisparitySrvRequest
typedef  ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<std::allocator<void> > Get3DPointFromDisparitySrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest> Get3DPointFromDisparitySrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest const> Get3DPointFromDisparitySrvRequestConstPtr;



template <class ContainerAllocator>
struct Get3DPointFromDisparitySrvResponse_ {
  typedef Get3DPointFromDisparitySrvResponse_<ContainerAllocator> Type;

  Get3DPointFromDisparitySrvResponse_()
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  Get3DPointFromDisparitySrvResponse_(const ContainerAllocator& _alloc)
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  typedef float _X_type;
  float X;

  typedef float _Y_type;
  float Y;

  typedef float _Z_type;
  float Z;


  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct Get3DPointFromDisparitySrvResponse
typedef  ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<std::allocator<void> > Get3DPointFromDisparitySrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse> Get3DPointFromDisparitySrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse const> Get3DPointFromDisparitySrvResponseConstPtr;


struct Get3DPointFromDisparitySrv
{

typedef Get3DPointFromDisparitySrvRequest Request;
typedef Get3DPointFromDisparitySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Get3DPointFromDisparitySrv
} // namespace compsci403_assignment2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ef6b969e35b4a5895bcc150a21ed53f9";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xef6b969e35b4a589ULL;
  static const uint64_t static_value2 = 0x5bcc150a21ed53f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDisparitySrvRequest";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
int32 disparity\n\
float32 fx\n\
float32 fy\n\
float32 px\n\
float32 py\n\
float32 a\n\
float32 b\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1dfb8f61d81d8e9fe291bc0d86a2f48";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1dfb8f61d81d8e9ULL;
  static const uint64_t static_value2 = 0xfe291bc0d86a2f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDisparitySrvResponse";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.disparity);
    stream.next(m.fx);
    stream.next(m.fy);
    stream.next(m.px);
    stream.next(m.py);
    stream.next(m.a);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Get3DPointFromDisparitySrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.X);
    stream.next(m.Y);
    stream.next(m.Z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Get3DPointFromDisparitySrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDisparitySrv> {
  static const char* value() 
  {
    return "d24a10f36ae66a6817e2dc64457fcb83";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment2::Get3DPointFromDisparitySrv> {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d24a10f36ae66a6817e2dc64457fcb83";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d24a10f36ae66a6817e2dc64457fcb83";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDISPARITYSRV_H

