/* Auto-generated by genmsg_cpp for file /home/rpg711/kinetic_workspace/cs403/compsci403_assignment2/srv/Get3DPointFromDepthSrv.srv */
#ifndef COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDEPTHSRV_H
#define COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDEPTHSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace compsci403_assignment2
{
template <class ContainerAllocator>
struct Get3DPointFromDepthSrvRequest_ {
  typedef Get3DPointFromDepthSrvRequest_<ContainerAllocator> Type;

  Get3DPointFromDepthSrvRequest_()
  : x(0)
  , y(0)
  , depth(0.0)
  , fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  {
  }

  Get3DPointFromDepthSrvRequest_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , depth(0.0)
  , fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef float _depth_type;
  float depth;

  typedef float _fx_type;
  float fx;

  typedef float _fy_type;
  float fy;

  typedef float _px_type;
  float px;

  typedef float _py_type;
  float py;


  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct Get3DPointFromDepthSrvRequest
typedef  ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<std::allocator<void> > Get3DPointFromDepthSrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest> Get3DPointFromDepthSrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest const> Get3DPointFromDepthSrvRequestConstPtr;



template <class ContainerAllocator>
struct Get3DPointFromDepthSrvResponse_ {
  typedef Get3DPointFromDepthSrvResponse_<ContainerAllocator> Type;

  Get3DPointFromDepthSrvResponse_()
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  Get3DPointFromDepthSrvResponse_(const ContainerAllocator& _alloc)
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  typedef float _X_type;
  float X;

  typedef float _Y_type;
  float Y;

  typedef float _Z_type;
  float Z;


  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct Get3DPointFromDepthSrvResponse
typedef  ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<std::allocator<void> > Get3DPointFromDepthSrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse> Get3DPointFromDepthSrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse const> Get3DPointFromDepthSrvResponseConstPtr;


struct Get3DPointFromDepthSrv
{

typedef Get3DPointFromDepthSrvRequest Request;
typedef Get3DPointFromDepthSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Get3DPointFromDepthSrv
} // namespace compsci403_assignment2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e19d45c84759bd9a2b24a15e4f917079";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe19d45c84759bd9aULL;
  static const uint64_t static_value2 = 0x2b24a15e4f917079ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDepthSrvRequest";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
float32 depth\n\
float32 fx\n\
float32 fy\n\
float32 px\n\
float32 py\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1dfb8f61d81d8e9fe291bc0d86a2f48";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1dfb8f61d81d8e9ULL;
  static const uint64_t static_value2 = 0xfe291bc0d86a2f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDepthSrvResponse";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.depth);
    stream.next(m.fx);
    stream.next(m.fy);
    stream.next(m.px);
    stream.next(m.py);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Get3DPointFromDepthSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.X);
    stream.next(m.Y);
    stream.next(m.Z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Get3DPointFromDepthSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDepthSrv> {
  static const char* value() 
  {
    return "fa92684c4d3e22b7bf75527d69a8eb73";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment2::Get3DPointFromDepthSrv> {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDepthSrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fa92684c4d3e22b7bf75527d69a8eb73";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDepthSrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fa92684c4d3e22b7bf75527d69a8eb73";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/Get3DPointFromDepthSrv";
  }

  static const char* value(const compsci403_assignment2::Get3DPointFromDepthSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT2_SERVICE_GET3DPOINTFROMDEPTHSRV_H

