/* Auto-generated by genmsg_cpp for file /home/rpg711/kinetic_workspace/cs403/compsci403_assignment2/srv/GetDepthFromDisparitySrv.srv */
#ifndef COMPSCI403_ASSIGNMENT2_SERVICE_GETDEPTHFROMDISPARITYSRV_H
#define COMPSCI403_ASSIGNMENT2_SERVICE_GETDEPTHFROMDISPARITYSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace compsci403_assignment2
{
template <class ContainerAllocator>
struct GetDepthFromDisparitySrvRequest_ {
  typedef GetDepthFromDisparitySrvRequest_<ContainerAllocator> Type;

  GetDepthFromDisparitySrvRequest_()
  : disparity(0)
  , a(0.0)
  , b(0.0)
  {
  }

  GetDepthFromDisparitySrvRequest_(const ContainerAllocator& _alloc)
  : disparity(0)
  , a(0.0)
  , b(0.0)
  {
  }

  typedef int32_t _disparity_type;
  int32_t disparity;

  typedef float _a_type;
  float a;

  typedef float _b_type;
  float b;


  typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetDepthFromDisparitySrvRequest
typedef  ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<std::allocator<void> > GetDepthFromDisparitySrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest> GetDepthFromDisparitySrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest const> GetDepthFromDisparitySrvRequestConstPtr;



template <class ContainerAllocator>
struct GetDepthFromDisparitySrvResponse_ {
  typedef GetDepthFromDisparitySrvResponse_<ContainerAllocator> Type;

  GetDepthFromDisparitySrvResponse_()
  : depth(0.0)
  {
  }

  GetDepthFromDisparitySrvResponse_(const ContainerAllocator& _alloc)
  : depth(0.0)
  {
  }

  typedef float _depth_type;
  float depth;


  typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetDepthFromDisparitySrvResponse
typedef  ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<std::allocator<void> > GetDepthFromDisparitySrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse> GetDepthFromDisparitySrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse const> GetDepthFromDisparitySrvResponseConstPtr;


struct GetDepthFromDisparitySrv
{

typedef GetDepthFromDisparitySrvRequest Request;
typedef GetDepthFromDisparitySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetDepthFromDisparitySrv
} // namespace compsci403_assignment2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a6648495a269e8a39999c87272be64f9";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa6648495a269e8a3ULL;
  static const uint64_t static_value2 = 0x9999c87272be64f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetDepthFromDisparitySrvRequest";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 disparity\n\
float32 a\n\
float32 b\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6deb06b7b7183f5581b3362a0cb413b7";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6deb06b7b7183f55ULL;
  static const uint64_t static_value2 = 0x81b3362a0cb413b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetDepthFromDisparitySrvResponse";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 depth\n\
\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.disparity);
    stream.next(m.a);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct GetDepthFromDisparitySrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.depth);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct GetDepthFromDisparitySrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment2::GetDepthFromDisparitySrv> {
  static const char* value() 
  {
    return "4eb644ec455b55a777cc3c887868dbf9";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment2::GetDepthFromDisparitySrv> {
  static const char* value() 
  {
    return "compsci403_assignment2/GetDepthFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4eb644ec455b55a777cc3c887868dbf9";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetDepthFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4eb644ec455b55a777cc3c887868dbf9";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetDepthFromDisparitySrv";
  }

  static const char* value(const compsci403_assignment2::GetDepthFromDisparitySrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT2_SERVICE_GETDEPTHFROMDISPARITYSRV_H

