/* Auto-generated by genmsg_cpp for file /home/rpg711/kinetic_workspace/cs403/compsci403_assignment2/srv/GetIntrinsicsSrv.srv */
#ifndef COMPSCI403_ASSIGNMENT2_SERVICE_GETINTRINSICSSRV_H
#define COMPSCI403_ASSIGNMENT2_SERVICE_GETINTRINSICSSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace compsci403_assignment2
{
template <class ContainerAllocator>
struct GetIntrinsicsSrvRequest_ {
  typedef GetIntrinsicsSrvRequest_<ContainerAllocator> Type;

  GetIntrinsicsSrvRequest_()
  {
  }

  GetIntrinsicsSrvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetIntrinsicsSrvRequest
typedef  ::compsci403_assignment2::GetIntrinsicsSrvRequest_<std::allocator<void> > GetIntrinsicsSrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvRequest> GetIntrinsicsSrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvRequest const> GetIntrinsicsSrvRequestConstPtr;



template <class ContainerAllocator>
struct GetIntrinsicsSrvResponse_ {
  typedef GetIntrinsicsSrvResponse_<ContainerAllocator> Type;

  GetIntrinsicsSrvResponse_()
  : fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  , a(0.0)
  , b(0.0)
  {
  }

  GetIntrinsicsSrvResponse_(const ContainerAllocator& _alloc)
  : fx(0.0)
  , fy(0.0)
  , px(0.0)
  , py(0.0)
  , a(0.0)
  , b(0.0)
  {
  }

  typedef float _fx_type;
  float fx;

  typedef float _fy_type;
  float fy;

  typedef float _px_type;
  float px;

  typedef float _py_type;
  float py;

  typedef float _a_type;
  float a;

  typedef float _b_type;
  float b;


  typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetIntrinsicsSrvResponse
typedef  ::compsci403_assignment2::GetIntrinsicsSrvResponse_<std::allocator<void> > GetIntrinsicsSrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvResponse> GetIntrinsicsSrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment2::GetIntrinsicsSrvResponse const> GetIntrinsicsSrvResponseConstPtr;


struct GetIntrinsicsSrv
{

typedef GetIntrinsicsSrvRequest Request;
typedef GetIntrinsicsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetIntrinsicsSrv
} // namespace compsci403_assignment2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetIntrinsicsSrvRequest";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "41c1a913ab0768dc23cb054cfa8156c5";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x41c1a913ab0768dcULL;
  static const uint64_t static_value2 = 0x23cb054cfa8156c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetIntrinsicsSrvResponse";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 fx\n\
float32 fy\n\
float32 px\n\
float32 py\n\
float32 a\n\
float32 b\n\
\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct GetIntrinsicsSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.fx);
    stream.next(m.fy);
    stream.next(m.px);
    stream.next(m.py);
    stream.next(m.a);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct GetIntrinsicsSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment2::GetIntrinsicsSrv> {
  static const char* value() 
  {
    return "41c1a913ab0768dc23cb054cfa8156c5";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment2::GetIntrinsicsSrv> {
  static const char* value() 
  {
    return "compsci403_assignment2/GetIntrinsicsSrv";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "41c1a913ab0768dc23cb054cfa8156c5";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetIntrinsicsSrv";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "41c1a913ab0768dc23cb054cfa8156c5";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment2/GetIntrinsicsSrv";
  }

  static const char* value(const compsci403_assignment2::GetIntrinsicsSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT2_SERVICE_GETINTRINSICSSRV_H

