(cl:defpackage compsci403_assignment4-srv
  (:use )
  (:export
   "GETFREEPATHSRV"
   "<GETFREEPATHSRV-REQUEST>"
   "GETFREEPATHSRV-REQUEST"
   "<GETFREEPATHSRV-RESPONSE>"
   "GETFREEPATHSRV-RESPONSE"
   "GETCOMMANDVELSRV"
   "<GETCOMMANDVELSRV-REQUEST>"
   "GETCOMMANDVELSRV-REQUEST"
   "<GETCOMMANDVELSRV-RESPONSE>"
   "GETCOMMANDVELSRV-RESPONSE"
   "CHECKPOINTSRV"
   "<CHECKPOINTSRV-REQUEST>"
   "CHECKPOINTSRV-REQUEST"
   "<CHECKPOINTSRV-RESPONSE>"
   "CHECKPOINTSRV-RESPONSE"
  ))

